### ISSUE TITLE
Error 400 Bad Request with culture with decimal seperator

### ISSUE THREAD

**Issue by sbiaudet** [AlienDwarf/open-meteo-dotnet#19]
When you use openmeteo.dotnet with a culture configured with a decimal separator the request is not correctly build and open-meteo server response an error 400.

I've tested it with French Culture "fr-FR"

**Comment by AlienDwarf** [comment]
Thanks for the report!

[InvariantCulture](https://learn.microsoft.com/en-us/dotnet/api/system.globalization.cultureinfo.invariantculture?view=net-7.0) is by far the better approach since it's not associated with any regional settings.

**Comment by sbiaudet** [comment]
You're welcome !!

I've seen some others possible improvements. I'll back to you with more PR ;)
