### ISSUE TITLE
Add European AQI and US AQI

### ISSUE THREAD

**Issue by sbiaudet** [AlienDwarf/open-meteo-dotnet#21]
European AQI parameters and US AQI parameters are not supported by library. 

Parameters available for European AQI :
- european_aqi
- european_aqi_pm2_5
- european_aqi_pm10
- european_aqi_no2
- european_aqi_o3
- european_aqi_so2

Parameters available for US AQI :
- us_aqi
- us_aqi_pm2_5
- us_aqi_pm10
- us_aqi_no2
- us_aqi_o3
- us_aqi_so2
- us_aqi_co

**Comment by AlienDwarf** [comment]
Thank you very much ! :)

Edit: I wasn't able to merge the last 2 days. Looks good and all tests passed so I will merge it. It will become available in [v0.2.6](https://github.com/AlienDwarf/open-meteo-dotnet/releases/tag/0.2.6) 😄
