### ISSUE TITLE
Make HourlyOptions and DailyOptions enumerable

### ISSUE THREAD

**Issue by AlienDwarf** [AlienDwarf/open-meteo-dotnet#7]
### Description
Implement interface `IEnumerable`

### Describe the solution you'd like
Possibility to use `for each`

**Comment by DadiBit** [comment]
Not sure how easy the "translation" would be, but you should be able to ease a bit the work by copying and pasting from the [kotlin library](https://github.com/open-meteo/open-meteo-api-kotlin/tree/main/lib/src/main/kotlin/com/openmeteo/api).
All enums are in the `params` subfolders, btw :smile:

**Comment by AlienDwarf** [comment]
Thank you for the hint😄
 I think there will be some code to recycle.

Otherwise we will still have to implement [IEnumerable](https://docs.microsoft.com/en-us/dotnet/api/system.collections.ienumerable?view=net-6.0) and probably [ICollection](https://docs.microsoft.com/en-us/dotnet/api/system.collections.icollection?view=net-6.0) to make for-each-loop work in c#.

Feel free to fork if you want :D

**Comment by DadiBit** [comment]
> Otherwise we will still have to implement [IEnumerable](https://docs.microsoft.com/en-us/dotnet/api/system.collections.ienumerable?view=net-6.0) and probably [ICollection](https://docs.microsoft.com/en-us/dotnet/api/system.collections.icollection?view=net-6.0) to make for-each-loop work in c#.
> 
> Feel free to fork if you want :D

I'm sorry, I've never worked in C# (only a bit with .NET on PowerShell). I'm also working on the Kotlin library (which wasn't too difficult to learn, since I worked with Java and JavaScript), so it would be quite difficult for me to be of any other help.

As a sidenote: I really like the structure of this library (like the fact that you can use a place name instead of its coordinates), so I'm thinking of stealing the code structure; hope you don't mind :)

**Comment by AlienDwarf** [comment]
> As a sidenote: I really like the structure of this library (like the fact that you can use a place name instead of its coordinates), so I'm thinking of stealing the code structure; hope you don't mind :)

No problem go ahead, keep in mind you have to make 2 requests to get weather data of a location by it's name 😄

**Comment by DadiBit** [comment]
I was thinking about using the main constructor with the coordinates and then overloading it with one that sets some default coordinates and then queries the geocoding API.
Not sure if it could work in C#, but I think it would be a nice feature in this library as well.

**Comment by AlienDwarf** [comment]
I'm not sure if you meant this but `WeatherForecastOptions options = new WeatherForecastOptions();` already sets latitude and longitude to 0 as default location. If you now query weather data with this options you will get weather data 😁
